version: '3.8'  # Mantive a versão mais recente

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: dbproject.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: senha_segura
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wp_data:/var/www/html

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=fs-1234567c8910e8485.efs.us-east-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      device: ":/"
